### ISSUE TITLE
the Release is guaranteed to  immediately take effect on other threads?

### ISSUE THREAD

**Issue by star4evar** [cfsamson/articles-atomics-in-rust#6]
in the 'Release' part,  it is said that:
So not only do the operations need to be correctly ordered locally,
there is also a guarantee that the changes must be visible to an observing core at this point.

however, there is an example from this video, from 1:35:
https://www.youtube.com/watch?v=rMGWeSjctlY
```
fn main(){
    use std::sync::atomic::AtomicUsize;
    let x: &'static _ = Box::leak(Box::new(AtomicBool::new(false)));
    let y: &'static _ = Box::leak(Box::new(AtomicBool::new(false)));
    let z: &'static _ = Box::leak(Box::new(AtomicUsize::new(0)));

    let _tx = spawn(move ||{
        x.store(true, Ordering::Release);
    });

    let _ty = spawn(move ||{
        y.store(true, Ordering::Release);
    });

    let t1 = spawn(move ||{
        while !x.load(Ordering::Acquire){}
        if y.load(Ordering::Acquire){
            z.fetch_add(1, Ordering::Relaxed);
        }
    });

    let t2 = spawn(move ||{
        while !y.load(Ordering::Acquire){}
        if x.load(Ordering::Acquire){
            z.fetch_add(1, Ordering::Relaxed);
        }
    });

    t1.join().unwrap();
    t2.join().unwrap();
    let z = z.load(Ordering::SeqCst);
    println!("z is: {}", z);
}
```
according to what the author claimed, the result of z might be 0
the above example is a classic demo, so I believe their conclusion is correct.
however it is inconsistent with your statement that "there is also a guarantee that the changes must be visible to an observing core at this point"
and here is the explanation:
let we suppose the guarantee does exist,
let we name "if y.load(Ordering::Acquire)" in t1  as statement1,  and  "if x.load(Ordering::Acquire)" in t2  as statement2.
if statement1 and statement2 happens exactly at the same cpu clock cycle,
      then x and y should both have been set to true at that point, otherwise they couldn't reach there.
      since the store(Release) is visible immediately for load(Acquire), both statement1 and statement2 will
       load x and y as true, and inc z by 1.
if statement1 and statement2 happens one after another, suppose t1 reaches statement1 first,
      when t2 reaches statement2, as t1 has reaches statement1 earlier, we know that x has already been set to true.
      then t2 will inc z by 1.
      likewise , if t2 reaches statement2 earlier than statement1, then t1 will inc z by 1.
therefore z could never be 0 as per your guarantee
so I guess maybe the guarantee does not exist for weakly ordered CPU?

**Comment by cfsamson** [comment]
I'm sorry, but I don't have the bandwidth to revisit this article at the moment. You've made an excellent observation, though. I've tried to put of some time for this, but haven't managed it yet. I just wanted to let you know that I've seen you issue, and it might very well be that my wording is imprecise, or in the worst case wrong, in the paragraph you're referring to. 

The major complication is that while the change to a memory location must be observed by an observing core at the point of `Release` it doesn't promise that changes to two unrelated locations in memory must be seen in any specific order. They can in theory hold different versions of the truth at the point of unrelated `Acquire` memory accesses (which is why  `z` can be zero). 

I think this is the best explanation of the different memory orderings that I've come across so I'll refer you to that instead of trying to reinvent the wheel: https://preshing.com/20120710/memory-barriers-are-like-source-control-operations/

>so I guess maybe the guarantee does not exist for weakly ordered CPU?

The memory model is meant to abstract over different CPU architectures, so the rules we discuss here are meant to be valid for all CPU's that comply with the C memory model (whether they have a weak or strong model).

**Comment by star4evar** [comment]
the article you mentioned is interesting , thanks man!
